joint_state_controller:
  type: "joint_state_controller/JointStateController"
  publish_rate: 50




# Controller to control robot base joints
left_wheel_joint_velocity_controller:
  type: "velocity_controllers/JointVelocityController"
  joint: "left_joint"
  pid: {p: 100.0, i: 0.1, d: 10.0}

right_wheel_joint_velocity_controller:
  type: "velocity_controllers/JointVelocityController"
  joint: "right_joint"
  pid: {p: 100.0, i: 0.1, d: 10.0}

# Velocity Controller for Prismatic Joint
prismatic_controller:
  type: velocity_controllers/JointVelocityController
  joint: prismatic
  pid: {p: 50.0, i: 0.05, d: 5.0}

# Velocity Controller for Rotation Joint
rotation_controller:
  type: velocity_controllers/JointVelocityController
  joint: rotation
  pid: {p: 50.0, i: 0.05, d: 5.0}

  